### ISSUE TITLE
Query regarding Python 2.7 End-Of-Life approaching

### ISSUE THREAD

**Issue by JarmBlueOak** [upsidetravel/bucket-antivirus-function#101]
Just wondering with Python 2.7 EOL approaching and how pro-active AWS are with phasing out EOL runtimes from Lambda (eg recently Node 8.x) if you guys were planning to update the github code base to 3.x or leave as 2.7 for the forseeable future.

Love this solution and appreciate that you released it open source, it has been very helpful.

**Comment by chrisgilmerproj** [comment]
@JarmBlueOak - I do have a plan to upgrade to 3.X. I hope to do it in the next couple weeks but I have to find time. We have some good PRs already for this I just need to bring them up to date. Thanks for asking!

**Comment by JarmBlueOak** [comment]
@chrisgilmerproj - Appreciate the reply, great to hear regarding 3.x updates to come. Will keep an eye out.
