### ISSUE TITLE
Deprecation of python 2 and upgrade to python 3 https://pythonclock.org/

### ISSUE THREAD

**Issue by kickthedragon** [upsidetravel/bucket-antivirus-function#104]
It seems theres going to be an inevitable incompatibility with this repo moving forward since Python 2 is being deprecated in one month and will no longer receive any updates including severe security issues.

https://pythonclock.org/

https://www.python.org/doc/sunset-python-2/ 

When a language is deprecated AWS also removes support for creating new lambda functions and editing functions with that runtime. So they should be sending out emails shortly telling users to update their functions to python 3.

it does seem there are pull requests that are attempting to address this issue.

https://github.com/upsidetravel/bucket-antivirus-function/pull/71 & https://github.com/upsidetravel/bucket-antivirus-function/pull/74

**Comment by JarmBlueOak** [comment]
Hey @kickthedragon, there are also some relevant replies related to your query in a ticket I logged #101.

**Comment by chrisgilmerproj** [comment]
I believe that #107 has solved this for you.
