### ISSUE TITLE
daily file is downloaded as daily.cld in the update function, which doesnt update a daily.cvd

### ISSUE THREAD

**Issue by joshlove** [upsidetravel/bucket-antivirus-function#11]
--edit: It's still downloading as daily.cld even with the compress local db option on, digging into that since it's not actually updating the bucket regardless.

**Comment by denniswebb** [comment]
Great find!  cvd is the compressed format, cld is the uncompressed format.  Freshclam is decompressing the cvd to a cld, then updating it with a diff file.  I will modify to support both file formats.  If both extensions are present, clamav will check the version and use the latest one.
