### ISSUE TITLE
Clam Av No Longer Updating

### ISSUE THREAD

**Issue by Jayshunnn** [upsidetravel/bucket-antivirus-function#117]
Hello

Our team has had no problem updating to the latest version of clamAV up until about 6 months ago.
 
Now the logs are giving us the OUTDATED message from clamAv when trying to update from `0.101.5` to `0.102.2` and rebuilding the repo is not working like it had previously.

The  definitions have no problem updating

**Comment by Jayshunnn** [comment]
It appears it was an issue with the Amazon Linux Distro and inclusion of Centos 7 not having a relevant GPG key for ClamAv102.2

this issue has been solved with the use of `--nogpgcheck` option next to the `yumdownloader clamav`

NOTE: we are using an older version of the repo

**Comment by sravankml** [comment]
I'm also getting error on updating AV definition.Can anyone please help me to resolve this issue  

```
daily database available for update (local version: 25901, remote version: 25904)
ERROR: cdiff_cmd_close: Can't write to ./clamav-a254916a90d57256096c9e1a76134926.tmp
ERROR: cdiff_apply: Can't execute command CLOSE
ERROR: cdiff_apply: Error executing command at line 66285
ERROR: downloadPatch: Can't apply patch
WARNING: Incremental update failed, trying to download daily.cvd
ERROR: Download failed (23) ERROR:  Message: Failed writing received data to disk/application
ERROR: getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Giving up on https://database.clamav.net...
ERROR: Update failed for database: daily
WARNING: fc_update_databases: fc_update_database failed: Connection failed (5)
ERROR: Database update process failed: Connection failed (5)
ERROR: Update failed

Unexpected exit code from freshclam: 5.
```
