### ISSUE TITLE
daily.cud and bytecode.cud files missing

### ISSUE THREAD

**Issue by akshay3004** [upsidetravel/bucket-antivirus-function#15]
After running the `bucket-antivirus-update` lambda function, there were only these files in the `clamav_defs` folder:
- `main.cvd`
- `daily.cvd`
- `bytecode.cvd`

There were no files named `daily.cud` and `bytecode.cud` which caused the `bucket-antivirus-function` lambda function to give an error in downloading these files.

For now, I have removed these 2 files from https://github.com/upsidetravel/bucket-antivirus-function/blob/master/common.py#L31 and it works fine.

I see that this is a recent change. Is the current master not stable? Let me know if I am missing something

**Comment by denniswebb** [comment]
Master should be stable, but there is definitely an issue.  Working on a solution this afternoon.  Thanks for the report.

**Comment by akshay3004** [comment]
👍
