### ISSUE TITLE
No supported database files found in /tmp/clamav_defs

### ISSUE THREAD

**Issue by turingbeing** [upsidetravel/bucket-antivirus-function#189]
LibClamAV Error: cli_loaddbdir(): No supported database files found in /tmp/clamav_defs

Built using the instructions, including the updated Dockerfile as mentioned in another issue.

I am using v2.0.0 branch

Any help?

**Comment by dwc0011** [comment]
> LibClamAV Error: cli_loaddbdir(): No supported database files found in /tmp/clamav_defs
> 
> Built using the instructions, including the updated Dockerfile as mentioned in another issue.
> 
> I am using v2.0.0 branch
> 
> Any help?

I am not a maintainer but I do use this, I would say probably a permissions issue, can you view the CloudWatch logs for updater lambda?

**Comment by turingbeing** [comment]
I actually figured it out.

I was using a custom prefix for the Definitions, but in the method that downloads the definitions in the Scanning lambda, the `prefix` is passed to the function, but never actually used, I removed the ENV Vars, and off it went :shrug:
