### ISSUE TITLE
Intermittent failures

### ISSUE THREAD

**Issue by jonmelia** [upsidetravel/bucket-antivirus-function#19]
On both the scan file function and update operation I'm seeing Head operation failures.  The update works the first time and then starts to return Head operation failures  I'm aware this seems to be an S3 permission issue, but I can't identify why this works the first time and then stops working. An error occurred (403) when calling the HeadObject operation: Forbidden: ClientError
Traceback (most recent call last):
File "/var/task/scan.py", line 100, in lambda_handler
clamav.update_defs_from_s3(AV_DEFINITION_S3_BUCKET, AV_DEFINITION_S3_PREFIX)
File "/var/task/clamav.py", line 39, in update_defs_from_s3
s3.Bucket(bucket).download_file(s3_path, local_path)
File "/var/runtime/boto3/s3/inject.py", line 168, in bucket_download_file
ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
File "/var/runtime/boto3/s3/inject.py", line 130, in download_file
extra_args=ExtraArgs, callback=Callback)
File "/var/runtime/boto3/s3/transfer.py", line 307, in download_file
future.result()
File "/var/runtime/s3transfer/futures.py", line 73, in result
return self._coordinator.result()
File "/var/runtime/s3transfer/futures.py", line 233, in result
raise self._exception
ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by denniswebb** [comment]
This appears to be a permissions issue with the bucket you're using for antivirus definitions.  Can you add the IAM policy section for bucket access used by the function?

**Comment by jonmelia** [comment]
See below:  Acct details redacted
{
    "Version": "2012-10-17",
    "Id": "Policynnnnnnnnnnnn",
    "Statement": [
        {
            "Sid": "MySid",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::Acctnumber:root",
                ]
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::bucketname/*"
        }
    ]
}

**Comment by jonmelia** [comment]
For some reason the copy has removed the asterisk from after the s3: in the above comment and changed the formatting

**Comment by chrisgilmerproj** [comment]
I believe if you check out the README.md you'll see the most up-to-date IAM policy recommendations. Hopefully that will get you what you need, `s3:ListBucket`, for working around [the `HeadObject` issue](https://github.com/upsidetravel/bucket-antivirus-function#definition-update-lambda).
