### ISSUE TITLE
Send only message to SNS if av-status = INFECTED

### ISSUE THREAD

**Issue by scholdborg** [upsidetravel/bucket-antivirus-function#29]
Hi, is it possible to send a message to SNS if the av-status is INFECTED? It works fine to publish to SNS with the original code (both clean and infected).

I've tried to add:
    if result == AV_STATUS_CLEAN:
        return

Under def sns_scan_results in common.py but get this error:

An error occurred (403) when calling the HeadObject operation: Forbidden: ClientError Traceback (most recent call last): File "/var/task/scan.py", line 146, in lambda_handler sns_scan_results(s3_object, scan_result) File "/var/task/scan.py", line 120, in sns_scan_results "version": s3_object.version_id, File "/var/runtime/boto3/resources/factory.py", line 339, in property_loader

**Comment by HollywoodMarks** [comment]
If you only want to send the SNS when infected, I would change line 144 in scan.py to 

if scan_result == "INFECTED":
        sns_scan_results(s3_object, scan_result)

Or, you could change it within the function sns_scan_results to start with the same if statement.

**Comment by madcat78** [comment]
I think you should send a SNS notification before tagging the S3 object.
If you have a deny policy for infected files the lambda itself will not perform any read operation and cannot notify SNS.

Try this way:
`diff --git a/scan.py b/scan.py
index fd7315f..8e74eae 100644
--- a/scan.py
+++ b/scan.py
@@ -140,8 +140,9 @@ def lambda_handler(event, context):
     print("Scan of s3://%s resulted in %s\n" % (os.path.join(s3_object.bucket_name, s3_object.key), scan_result))
     if "AV_UPDATE_METADATA" in os.environ:
         set_av_metadata(s3_object, scan_result)
+    if scan_result == "INFECTED":
+        sns_scan_results(s3_object, scan_result)
     set_av_tags(s3_object, scan_result)
-    sns_scan_results(s3_object, scan_result)
     metrics.send(env=ENV, bucket=s3_object.bucket_name, key=s3_object.key, status=scan_result)
     # Delete downloaded file to free up room on re-usable lambda function container
     try:`

**Comment by HollywoodMarks** [comment]
Another option is to go into the SNS Topic, and you can create a filter policy per Subscription, like so:
{"av-status": ["INFECTED"]}

**Comment by chrisgilmerproj** [comment]
I may have solved this one in https://github.com/upsidetravel/bucket-antivirus-function/pull/78
