### ISSUE TITLE
Is there a way to run the av check function for all existing files?

### ISSUE THREAD

**Issue by ocasta** [upsidetravel/bucket-antivirus-function#30]
It would be great to have an easy way to trigger the checking for all files in an S3 bucket. In our case this is because we already have lots of files in the bucket that need to be scanned before we can prevent download of files without the av-status:CLEAN tag

**Comment by noizo** [comment]
I'm interested in this question also.
Maybe there is a trigger to do that somehow?

**Comment by erecica** [comment]
Same here!

**Comment by KozyLigh** [comment]
Same here :)

**Comment by denniswebb** [comment]
You would need to write a script to invoke the lambda for each object already in the bucket. The script would need to send the s3 event metadata to the function.

If anybody is interested in writing the script, submit a PR and we can host it in the repo.

**Comment by gchamon** [comment]
You could change bucket encription at rest policy to trigger a createobject event. Disable your antivírus function first to prevent it running double when you turn encription back on again (or off)

**Comment by chrisgilmerproj** [comment]
I wrote a script for this and submitted it here: https://github.com/upsidetravel/bucket-antivirus-function/pull/79
