### ISSUE TITLE
Definitions Update Lambda fails on Test

### ISSUE THREAD

**Issue by rss0213** [upsidetravel/bucket-antivirus-function#31]
Getting the following error trying to run a test after I created the AV Definitions update Lambda.  Any idea what I did wrong?

START RequestId: e5822bad-6030-11e8-aaee-23e96b59c6e3 Version: $LATEST
Unable to import module 'update': No module named update

**Comment by SmartManoj** [comment]
The layer file name should be `python.zip`.

[Source](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-import-module-error-python/#:~:text=Important%3A%20Make%20sure,Resolution)
