### ISSUE TITLE
Current script doesn't work for amazon latest

### ISSUE THREAD

**Issue by Lacan82** [upsidetravel/bucket-antivirus-function#40]
Edit: Another Update after testing.

So, been trying to build this and ran into several issues with the latest image i pulled from docker following the instructions. I had to make the following changes to get it even COMPILE the zip. I am not sure if it even works. I'll update testing tomorrow. However, here are the changes

```
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
yum update -y
yum install yum-utils -y
yum install -y cpio python2-pip zip
pip install --no-cache-dir virtualenv
pip install --upgrade pip
virtualenv env
. env/bin/activate
pip install --no-cache-dir -r requirements.txt


pushd /tmp
yumdownloader -x \*i686 --archlist=x86_64 clamav clamav-lib clamav-update json-c pcre2
rpm2cpio pcre2*.rpm | cpio -idmv
rpm2cpio json-c*.rpm | cpio -idmv
rpm2cpio clamav-0*.rpm | cpio -idmv
rpm2cpio clamav-lib*.rpm | cpio -idmv
rpm2cpio clamav-update*.rpm | cpio -idmv
popd
mkdir -p bin
cp /tmp/usr/bin/clamscan /tmp/usr/bin/freshclam /tmp/usr/lib64/* bin/.
echo "DatabaseMirror database.clamav.net" > bin/freshclam.conf

mkdir -p build
zip -r9 $lambda_output_file *.py bin
cd env/lib/python2.7/site-packages
zip -r9 $lambda_output_file *
```

Short Version, Added Repo that included ClamAV, change Python27-pip to python2-pip, install yum-utils to get yumdownloader. Included json-c, pcre2

**Comment by gjacquetupgrade** [comment]
I just changed the build image tag to `2018.03.0.20180622` and it's building again for us.
I guess using `latest` is not the best idea when you need something stable!

**Comment by Lacan82** [comment]
All my script changes work with latest.

**Comment by gjacquetupgrade** [comment]
Thing is, by using latest, you do not for how long your changes will work. You can never know when another image will be pushed with tag latest and break the build again.
Amazon linux images are always pushed with a timestamp version tag that should never be updated.

I think that would be safer to use one of those tags rather than latest.

**Comment by Lacan82** [comment]
@gjacquetupgrade it might build, but have you tested the deploy? I know they say the execution amzn-ami-hvm-2017.03.1.20170812-x86_64-gp2. However, to get the functions working in lambda environment I had to include the two additional libraries. I would test this myself, but I am not home at the moment

**Comment by kennoosh** [comment]
> Edit: Another Update after testing.
> 
> So, been trying to build this and ran into several issues with the latest image i pulled from docker following the instructions. I had to make the following changes to get it even COMPILE the zip. I am not sure if it even works. I'll update testing tomorrow. However, here are the changes
> 
> ```
> yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
> yum update -y
> yum install yum-utils -y
> yum install -y cpio python2-pip zip
> pip install --no-cache-dir virtualenv
> pip install --upgrade pip
> virtualenv env
> . env/bin/activate
> pip install --no-cache-dir -r requirements.txt
> 
> 
> pushd /tmp
> yumdownloader -x \*i686 --archlist=x86_64 clamav clamav-lib clamav-update json-c pcre2
> rpm2cpio pcre2*.rpm | cpio -idmv
> rpm2cpio json-c*.rpm | cpio -idmv
> rpm2cpio clamav-0*.rpm | cpio -idmv
> rpm2cpio clamav-lib*.rpm | cpio -idmv
> rpm2cpio clamav-update*.rpm | cpio -idmv
> popd
> mkdir -p bin
> cp /tmp/usr/bin/clamscan /tmp/usr/bin/freshclam /tmp/usr/lib64/* bin/.
> echo "DatabaseMirror database.clamav.net" > bin/freshclam.conf
> 
> mkdir -p build
> zip -r9 $lambda_output_file *.py bin
> cd env/lib/python2.7/site-packages
> zip -r9 $lambda_output_file *
> ```
> Short Version, Added Repo that included ClamAV, change Python27-pip to python2-pip, install yum-utils to get yumdownloader. Included json-c, pcre2

Cool Man, it works with your updating.

**Comment by jaygorrell** [comment]
Fixed by https://github.com/upsidetravel/bucket-antivirus-function/pull/52
