### ISSUE TITLE
Update to Latest ClamAV 0.100.2

### ISSUE THREAD

**Issue by krishnaastica** [upsidetravel/bucket-antivirus-function#48]
Hello All,
How to update ClamAV to latest release 0.100.2.
Epel 7 supports only 0.100.1-3, is there a way to update to latest.
Thanks,
Krishh

**Comment by denniswebb** [comment]
Sorry for late response. I have confirmed Epel 7 now has `0.100.2-2`. You can always download the RPMs for another version of ClamAV by editing this line. https://github.com/upsidetravel/bucket-antivirus-function/blob/master/build_lambda.sh#L30
