### ISSUE TITLE
freshclam runs out of disk

### ISSUE THREAD

**Issue by nalbion** [upsidetravel/bucket-antivirus-function#49]
/tmp for Lambda functions is limited to 512MB. When I run freshclam in Lambda I get an error:

```
Downloading daily-25044.cdiff [100%]
Downloading daily-25045.cdiff [100%]
Downloading daily-25046.cdiff [100%]
ERROR: buildcld: Can't add daily.hsb to new daily.cld - please check if there is enough disk space available
ERROR: Can't create local database
```

**Comment by steeef** [comment]
Just ran into this myself. Seems definition files are now too large to fit in `/tmp`.

**Comment by nalbion** [comment]
We have clamd running on an ec2 instance for another project, so when it updates I get it to copy the files to S3, and my Lambda function updates from S3

**Comment by chrisgilmerproj** [comment]
I am hoping with merging of #63 that this is fixed. Can you run from master and see if that fixed it? Also make sure your IAM permissions are updated.
