### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by ztaff** [upsidetravel/bucket-antivirus-function#53]
This looks really interesting.
Now I have made two attempts to set this up.
First I tried with Ubuntu on my Windows bash prompt,
then I started a Ubuntu EC2 and did the Make there.
Same result:
Testing the Lambda i get an error:

`START RequestId: nnn-bnnn-nnnn-nnnn Version: $LATEST
Script starting at 2018/12/18 12:26:12 UTC

Attempting to create directiory /tmp/clamav_defs.

Starting freshclam with defs in /tmp/clamav_defs.
freshclam output:
./bin/freshclam: error while loading shared libraries: libjson-c.so.2: cannot open shared object file: No such file or directory

Unexpected exit code from freshclam: 127.
Script finished at 2018/12/18 12:26:12 UTC
...
`

Any ideas about how to get trough this?

**Comment by ocasta** [comment]
Changing build_lambda.sh as follows worked for me

`-yumdownloader -x \*i686 --archlist=x86_64 clamav clamav-lib clamav-update
+yumdownloader -x \*i686 --archlist=x86_64 clamav clamav-lib clamav-update json-c pcre2
+rpm2cpio pcre2*.rpm | cpio -idmv
+rpm2cpio json-c*.rpm | cpio -idmv
`

**Comment by ztaff** [comment]
@ocasta 
Thanks, it worked for me too.
Merry Xmas

**Comment by erecica** [comment]
> Changing build_lambda.sh as follows worked for me
> 
> ```
> -yumdownloader -x \*i686 --archlist=x86_64 clamav clamav-lib clamav-update
> +yumdownloader -x \*i686 --archlist=x86_64 clamav clamav-lib clamav-update json-c pcre2
> +rpm2cpio pcre2*.rpm | cpio -idmv
> +rpm2cpio json-c*.rpm | cpio -idmv
> ```

Worked fo me to. Thanx!

**Comment by github-abcde** [comment]
Did not work for me, the amazonlinux docker image does not have a pcre2 package. Using pcre worked just fine.

**Comment by chrisgilmerproj** [comment]
I believe this is fixed as evidenced by this code: https://github.com/upsidetravel/bucket-antivirus-function/blob/master/build_lambda.sh#L32-L37
