### ISSUE TITLE
getting below error bucket-antivirus-function

### ISSUE THREAD

**Issue by arushi-1234** [upsidetravel/bucket-antivirus-function#54]
START RequestId: 44a5bfce-0772-11e9-a343-cd0a75d4f9ef Version: $LATEST
Script starting at 2018/12/24 11:51:37 UTC

'Records': KeyError
Traceback (most recent call last):
  File "/var/task/scan.py", line 140, in lambda_handler
    s3_object = event_object(event)
  File "/var/task/scan.py", line 29, in event_object
    bucket = event['Records'][0]['s3']['bucket']['name']
KeyError: 'Records'

END RequestId: 44a5bfce-0772-11e9-a343-cd0a75d4f9ef
REPORT RequestId: 44a5bfce-0772-11e9-a343-cd0a75d4f9ef	Duration: 1.95 ms	Billed Duration: 100 ms 	Memory Size: 1152 MB	Max Memory Used: 61 MB

**Comment by denniswebb** [comment]
I'm assuming this is while testing the function in the AWS console? If so, can you share the event data you are passing to the function?

**Comment by arushi-1234** [comment]
I added AV_DEFINITION_S3_BUCKET value bucket name for both the functions

**Comment by arushi-1234** [comment]
Now getting below error

{
  "stackTrace": [
    [
      "/var/task/scan.py",
      145,
      "lambda_handler",
      "scan_result = clamav.scan_file(file_path)"
    ],
    [
      "/var/task/clamav.py",
      136,
      "scan_file",
      "raise Exception(msg)"
    ]
  ],
  "errorType": "Exception",
  "errorMessage": "Unexpected exit code from clamscan: 127.\n"
}

**Comment by chrisgilmerproj** [comment]
Can you try again with master? Make sure to update your IAM permissions. I'm going to close this because I think it should be fixed but I'll be happy to reopen and investigate.
