### ISSUE TITLE
env var for custom av-timestamp formatter?

### ISSUE THREAD

**Issue by AndrewLane** [upsidetravel/bucket-antivirus-function#59]
Hello, would you consider a PR that adds an optional env var that would allow you to configure the date formatting string on this line of code?

https://github.com/upsidetravel/bucket-antivirus-function/blob/1ed773e24779ba0fabc9cbfdf21909090962d132/scan.py#L67

Perhaps `AV_TIMESTAMP_FORMAT`?

**Comment by denniswebb** [comment]
Sure as long as the current format is the default if not set.
