### ISSUE TITLE
should not report unexpected exit code from freshclam when database is up-to-date

### ISSUE THREAD

**Issue by AndrewLane** [upsidetravel/bucket-antivirus-function#60]
I am seeing logs like this when my freshclam is up-to-date:

`Unexpected exit code from freshclam: 1.`

Should we update the code that checks for unexpected values to supplement the return code for "up-to-date"?

https://github.com/clamwin/clamav/blob/dcef52a6604dcbd864ba778734192b994d936d0b/freshclam/freshclamcodes.h#L25

**Comment by chrisgilmerproj** [comment]
Can you update and run with master and see if this fixes your issue? Also make sure to update your IAM permissions when doing so. If that doesn't fix it we'll be happy to re-open and investigate.
