### ISSUE TITLE
Project has no tests

### ISSUE THREAD

**Issue by jaygorrell** [upsidetravel/bucket-antivirus-function#72]
This project currently has no tests and due to internal bandwidth, it's difficult to keep up with requests and PRs largely because of that. If we can get a set of tests around the project we can do a better job keeping up with the demands.

**Comment by chrisgilmerproj** [comment]
@jaygorrell - If we use `nose` for tests is that acceptable? Or do you prefer a different tool?

**Comment by jaygorrell** [comment]
Works for me!

**Comment by jaygorrell** [comment]
Closed by https://github.com/upsidetravel/bucket-antivirus-function/pull/89
