### ISSUE TITLE
The bucket-antivirus-function timeouts when calling clamav

### ISSUE THREAD

**Issue by apedzko** [upsidetravel/bucket-antivirus-function#75]
Hi!

After installing the functions manually the function that downloads the clamav and definitions is working fine, however the function that is supposed to scan files hangs on calling the clamav.

The last message in the log is "Starting clamscan of /tmp/gfx-av-tests/test.txt." Then AWS kills the lambda when the execution time gets over the timeout (5 min in my case).

It looks like it is hanging after executing output = av_proc.communicate()[0]

Could you please advise what could be the issue?

**Comment by jamesrender50** [comment]
Also having this issue.  Does the scan lambda come with Clam AV for it to be initiated?

**Comment by apedzko** [comment]
@jamesrender50 It looks like it is.

**Comment by chrisgilmerproj** [comment]
Can you try again with the latest code from master? Also check that your IAM permissions are correct. There may have been an issue with downloading the ClamAV defs that we addressed in #96 . If that doesn't fix it we'll be happy to reopen and investigate.
