### ISSUE TITLE
generating clamscan file and lib files 

### ISSUE THREAD

**Issue by bobby-singh-oup** [upsidetravel/bucket-antivirus-function#81]
Hi, Just wanted to ask, how do you generate the clamav binaries which come as part of your package? Could you point us towards any documentation you use for this? We are looking at this solution as it looks powerful and want to build something similar (but not on Lambda due to the limits) but we are a little unclear on the best way to get the standalone One-Time Scanning clamscan file itself (and the various lib files) as generated by the clamav installation. (https://www.clamav.net/documents/scanning#one-time-scanning) These seem very useful standalone as we can see in your repo. 

To add a little more detail, we tried running the instructions here: 
https://www.clamav.net/documents/installing-clamav-on-unix-linux-macos-from-source

We installed ClamAv to a folder on a EC2  and found the standalone clamscan file here: 
/home/ec2-user/clamav-0.101.4/clamscan/.libs

We know that lib files are needed and found these in: 
/home/ec2-user/clamav-0.101.4/libclamav/.libs

The lib files I mean are (as can be seen in your package): 
libclamav.so.7
libclamav.so.7.1.1
libclammspack.so.0
libclammspack.so.0.1.0
libjson.so.0
libjson.so.0.1.0
libjson-c.so.2
libjson-c.so.2.0.1

How do we know which of these we need? Do those files need to be updated when ClamAv updates? 

I have somewhat reverse engineered the codebase here to see what is needed to run clamAv standalone (without installation) and I wonder if I am over complicating this.  I wonder if the clamscan file and the relevant libs are provided by ClamAv somewhere and I am simply overcomplicating matters by hacking away at the installation to get to the relevant files!  

Any guidance is very appreciated :)

**Comment by bobby-singh-oup** [comment]
To add a little more detail, we tried running the instructions here: 
https://www.clamav.net/documents/installing-clamav-on-unix-linux-macos-from-source

And while we managed to generate a clamscan file, it was much smaller than the one in this package and we were not able to identify the lib files.

**Comment by chrisgilmerproj** [comment]
No problem. All of this is done by [building inside a docker image using this script](https://github.com/upsidetravel/bucket-antivirus-function/blob/master/build_lambda.sh). Then the artifacts are copied out and added to the zip file. You can probably do the same thing with your project.

I don't believe those files need to be updated when ClamAV updates. You may be overcomplicating your issue so I'll point you to the [ClamAV Docs](https://www.clamav.net/documents/clam-antivirus-user-manual) for more information.
