### ISSUE TITLE
unquote_plus fails in 3.7

### ISSUE THREAD

**Issue by julian-berks** [upsidetravel/bucket-antivirus-function#86]
Running under Python 3.7

scan.py
[ERROR] AttributeError: module 'urllib' has no attribute 'unquote_plus'
Traceback (most recent call last):
  File "/var/task/scan.py", line 180, in lambda_handler
    s3_object = event_object(event)
  File "/var/task/scan.py", line 33, in event_object
    key = urllib.unquote_plus(event["Records"][0]["s3"]["object"]["key"].encode("utf8"))

Changed to (on my local copy)
key = urllib.parse.unquote_plus(event["Records"][0]["s3"]["object"]["key"])
and routine now runs correctly.

**Comment by ayozemr** [comment]
Add parse this way "urllib.parse.unquote_plus"

**Comment by chrisgilmerproj** [comment]
I'm pretty sure we're going to get to python3 support soon. But for now everything is still only set up to work with python2.  PRs #71 and #74 both address this and when we update to python3 we'll use those PRs as guidelines.
