### ISSUE TITLE
I created a terraform module that deploys the bucket antivirus function

### ISSUE THREAD

**Issue by gchamon** [upsidetravel/bucket-antivirus-function#88]
Hey there!

Took the liberty to automate the process of deploying this function. It does everything from compiling and deploying the code to a generic s3 bucket, creating the functions, setting the time trigger for the update function, configure the bucket event triggers for arbitrary, external buckets, as well as the necessary permissions for the lambda function to scan the bucket.

Now all there is to do is create the antivirus with a module like this:

```hcl
module "antivirus" {
  source = "gchamon/bucket-antivirus/aws"

  buckets-to-scan = [
    "my-test-bucket"
  ]

  scanner-environment-variables = {
    AV_DELETE_INFECTED_FILES = "True"
  }
  
  allow-public-access = true
}
```

All the environment variables are supported.

I wrote a deployment script based on your make script. I had to do that, because terraform executes bash code outside shell environment, so no TTY available for docker. This is why I needed more control over the code.

Here is the repository project: https://github.com/gchamon/terraform-aws-bucket-antivirus

Here is the terraform registry page: https://registry.terraform.io/modules/gchamon/bucket-antivirus/aws

I didn't include support for sns permissions yet, because in my original project I didn't need them and I couldn't write a test to assure that sns is correctly set, but with help I could update the project to include support for sns.

Hope you enjoy!

**Comment by chrisgilmerproj** [comment]
Would you mind taking a look at this terraform module that I created for this project? 

https://registry.terraform.io/modules/trussworks/s3-anti-virus/aws/2.0.0

It's terraform 12 ready and should work with the latest version of master. If its missing something you need I'd be happy to make changes/additions.

**Comment by gchamon** [comment]
Interesting. When I build thar project I couldn't find a terraform module already put together.

I believe the main difference is that I setup buckets with name prefix, so they never collide, and I compile the code from source and populate the lambdas automatically

**Comment by chrisgilmerproj** [comment]
> Interesting. When I build thar project I couldn't find a terraform module already put together.

Probably just ships passing in the night!

> I believe the main difference is that I setup buckets with name prefix, so they never collide, and I compile the code from source and populate the lambdas automatically

I think what you did there is a really neat trick. I've always done the lambda code separately from the TF code but I like what you've done. I probably won't update my module but I think it'd be great to link to a couple of these TF modules in the README. What do you think?

**Comment by gchamon** [comment]
nice! If we could document their differences, the user could opt between all of those.

another thing that came to mind, my module is not up to date with current modifications and I need to update it, because the scan function is not working quite right

**Comment by chrisgilmerproj** [comment]
I think if you update your IAM to get the `s3:ListBucket` like in the project readme you'll be set.

Would you like to make a PR with our modules and add it to the the README? I'd be happy to approve something like that.

**Comment by gchamon** [comment]
Sure! As soon as I feel my module is rock solid I will do it =D
