### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by jonmelia** [upsidetravel/bucket-antivirus-function#9]
I've been able to get the Update AV functionality working without issue, but keep running into this exception error when I upload a file to the bucket to be scanned..

Starting clamscan of /tmp/bucket/Testfile.txt.

./bin/clamscan: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory

Unexpected exit code from clamscan: 127.
: Exception
Traceback (most recent call last):
File "/var/task/scan.py", line 101, in lambda_handler
scan_result = clamav.scan_file(file_path)
File "/var/task/clamav.py", line 133, in scan_file
raise Exception(msg)
Exception: Unexpected exit code from clamscan: 127.

Any advice or pointers gratefully received

**Comment by denniswebb** [comment]
I'll try to test this soon and get back.

**Comment by jonmelia** [comment]
I have been able to resolve the Exception error, the Lambda.zip wasn't built correctly.  This works great.
