### ISSUE TITLE
Can't open database files in scanner function

### ISSUE THREAD

**Issue by gchamon** [upsidetravel/bucket-antivirus-function#95]
I have recently deployed the antivirus function to a new aws account, and I can't seem to scan files anymore:

```
Script starting at 2019/10/22 20:24:03 UTC

Downloading definition file main.cvd from s3://bucket-antivirus-definitions20191022185411604100000004/clamav_defs
Downloading definition file daily.cvd from s3://bucket-antivirus-definitions20191022185411604100000004/clamav_defs
Downloading definition file bytecode.cvd from s3://bucket-antivirus-definitions20191022185411604100000004/clamav_defs
Starting clamscan of /tmp/test-antivirus20191022185411604300000005/eicar.txt.
clamscan output:
LibClamAV Error: cli_loaddbdir(): No supported database files found in /tmp/clamav_defs
ERROR: Can't open file or directory

----------- SCAN SUMMARY -----------
Known viruses: 0
Engine version: 0.101.4
Scanned directories: 0
Scanned files: 0
Infected files: 0
Data scanned: 0.00 MB
Data read: 0.00 MB (ratio 0.00:1)
Time: 0.005 sec (0 m 0 s)
u'/tmp/test-antivirus20191022185411604300000005/eicar.txt': KeyError
Traceback (most recent call last):
File "/var/task/scan.py", line 228, in lambda_handler
scan_result, scan_signature = clamav.scan_file(file_path)
File "/var/task/clamav.py", line 199, in scan_file
signature = summary[path]
KeyError: u'/tmp/test-antivirus20191022185411604300000005/eicar.txt'
```

It seems that there is some problem with lambda accessing files in /tmp folder

**Comment by gchamon** [comment]
My last known working commit is 90b1061. Downgrading to this hash, code works again

**Comment by chrisgilmerproj** [comment]
Thank you for bringing this to me. Could you see if upgrading to master fixes this for you? Look at #93 and #96. Also ensure that your IAM policy is up to date. I'm going to close this but if that doesn't resolve the issue I'll be happy to reopen and investigate.

**Comment by nadavaviv** [comment]
I'm also experiencing similar problems
I'm trying to deploy clamscan on AWS Lambda, and whenever I try to invoke the function, I get the following message:
./bin/clamscan: error while loading shared libraries: libprelude.so.28: cannot open shared object file: No such file or directory

**Comment by JarmBlueOak** [comment]
hi @nadavaviv, see this ticket which resolved the issue for me:
https://github.com/upsidetravel/bucket-antivirus-function/issues/125

**Comment by nadavaviv** [comment]
@JarmBlueOak Worked like a charm :)
