### ISSUE TITLE
Starting freshclam with defs failing

### ISSUE THREAD

**Issue by chrismowbray** [upsidetravel/bucket-antivirus-function#97]
WIthin the last week I have noticed the update failing with the following error

`Can't add daily.mdb to new daily.cld - please check if there is enough disk space available` it looks like we have exceeded the Lambda 500mb limit here. I hadn't updated the package in a year or so so I updated and now see the following errors:

```
Starting freshclam with defs in /tmp/clamav_defs.
freshclam output:
ClamAV update process started at Tue Oct 29 13:25:29 2019
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
Downloading daily-25614.cdiff [100%]
ERROR: cdiff_cmd_close: Can't write to ./clamav-f9e93c076af9719bbedd7d8f184007e4.tmp
ERROR: cdiff_apply: Can't execute command CLOSE
ERROR: cdiff_apply: Error executing command at line 1578
ERROR: getpatch: Can't apply patch
WARNING: Incremental update failed, trying to download daily.cvd
Downloading daily.cvd [100%]tabase load killed by signal 9
ERROR: Failed to load new database
Unexpected exit code from freshclam: 55.
File does not exist: main.cld
```

**Comment by markmckim** [comment]
Hey @chrisgilmerproj - Is someone looking into this?

Or is there an ETA for a fix for this? We are no longer getting our daily updates either. Thanks!!!

**Comment by chrisgilmerproj** [comment]
Hi folks, sorry I missed this. Can you tell me if you updated your IAM policies for your lambdas? You now need this in order for them to work:

```
      {
         "Sid":"s3HeadObject",
         "Effect":"Allow",
         "Action":"s3:ListBucket",
         "Resource":[
             "arn:aws:s3:::<av-definition-s3-bucket>/*",
             "arn:aws:s3:::<av-definition-s3-bucket>"
         ]
      }
```

In #93 and #96 we made updates that would fix issues around downloading as well as fixing the policies.  I have a feeling this will fix things so I'm going to close the ticket. If it doesn't please let me know and I'll re-open and do more investigation.  As always, I appreciate that you are bringing these issues to us so we can make the tool better.

**Comment by markmckim** [comment]
Hey @chrisgilmerproj. Thanks for getting back to me. So this has been working fine for months, but only recently started failing, and we didn't change anything. However I did go and verify our IAM roles and can confirm that they do indeed have these permissions:

`
myProjectAntiVirusUpdateIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: myProjectAntiVirusUpdateRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: !Sub myProject-av-update-logging-${AppEnv}-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
                Effect: Allow
        - PolicyName: !Sub myProject-av-update-s3-${AppEnv}-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:GetObjectTagging
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:PutObjectTagging
                  - s3:PutObjectVersionTagging
                Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::${myProjectAvDefinitionBucket}
                  - !Sub arn:aws:s3:::${myProjectAvDefinitionBucket}/*
`

I've replaced a few variable names above with "myProject" and we are using params in our CFT but i've confirmed in the AWS Console that all permissions/roles are as expected and that the lambda does have the correct S3 permissions.

**Comment by chrisgilmerproj** [comment]
That is really odd. And you didn't update the code? Perhaps I'd suggest seeing if there's a traceback in the cloudwatch logs that we can dig into. Let's look at that and decide if we need to reopen.

**Comment by chrismowbray** [comment]
Hey @chrisgilmerproj no we didn't update the code and we started getting the `Can't add daily.mdb to new daily.cld - please check if there is enough disk space available` error. We then updated to the latest version. We are now getting the following warning 

`LibClamAV Warning: ***  The virus database is older than 7 days!  ***`

Here's one of our recent logs:

```
...
Attempting to create directory /tmp/clamav_defs.

Not downloading older file in series: bytecode.cvd
Downloading definition file /tmp/clamav_defs/main.cvd from s3://clamav_defs/main.cvd
Downloading definition file /tmp/clamav_defs/main.cvd complete!
Downloading definition file /tmp/clamav_defs/bytecode.cld from s3://clamav_defs/bytecode.cld
Downloading definition file /tmp/clamav_defs/bytecode.cld complete!
Downloading definition file /tmp/clamav_defs/daily.cvd from s3://clamav_defs/daily.cvd
Downloading definition file /tmp/clamav_defs/daily.cvd complete!
Starting freshclam with defs in /tmp/clamav_defs.
freshclam output:
ClamAV update process started at Thu Nov  7 03:12:09 2019
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
Downloading daily-25614.cdiff [100%]
Downloading daily-25615.cdiff [100%]
Downloading daily-25616.cdiff [100%]
Downloading daily-25617.cdiff [100%]
Downloading daily-25618.cdiff [100%]
Downloading daily-25619.cdiff [100%]
Downloading daily-25620.cdiff [100%]
Downloading daily-25621.cdiff [100%]
Downloading daily-25622.cdiff [100%]
Downloading daily-25623.cdiff [100%]
Downloading daily-25624.cdiff [100%]
Downloading daily-25625.cdiff [100%]

Unexpected exit code from freshclam: -9.
File does not exist: main.cld
Not uploading main.cvd because md5 on remote matches local.
File does not exist: daily.cld
Not uploading daily.cvd because md5 on remote matches local.
Not uploading bytecode.cld because md5 on remote matches local.
File does not exist: bytecode.cvd
Script finished at 2019/11/07 03:14:30 UTC
...
```

Maybe something to do with `Unexpected exit code from freshclam: -9.`

**Comment by chrisgilmerproj** [comment]
> Maybe something to do with `Unexpected exit code from freshclam: -9.`

I think you're right. I'd suggest boosting your memory on the lambda and see if that helps.

**Comment by markmckim** [comment]
Thanks @chrisgilmerproj - I have mine set to the default 512. What are you currently running yours at? Thanks!

**Comment by markmckim** [comment]
Also here is an excerpt from our logging:

```
Downloading definition file /tmp/clamav_defs/main.cvd complete!
Downloading definition file /tmp/clamav_defs/bytecode.cld from s3://clamav_defs/bytecode.cld
Downloading definition file /tmp/clamav_defs/bytecode.cld complete!
Downloading definition file /tmp/clamav_defs/daily.cvd from s3://clamav_defs/daily.cvd
Downloading definition file /tmp/clamav_defs/daily.cvd complete!
Starting freshclam with defs in /tmp/clamav_defs.
END RequestId: 8ec89e1a-4aa6-46b4-a722-ae768a1e8c6e
REPORT RequestId: 8ec89e1a-4aa6-46b4-a722-ae768a1e8c6e	Duration: 300100.08 ms	Billed Duration: 300000 ms	Memory Size: 512 MB	Max Memory Used: 512 MB	Init Duration: 447.93 ms	
2019-11-08T12:17:03.022Z 8ec89e1a-4aa6-46b4-a722-ae768a1e8c6e Task timed out after 300.10 seconds

START RequestId: 8ec89e1a-4aa6-46b4-a722-ae768a1e8c6e Version: $LATEST
Script starting at 2019/11/08 12:17:57 UTC

Not downloading main.cvd because local md5 matches s3.
Not downloading daily.cvd because local md5 matches s3.
Not downloading bytecode.cld because local md5 matches s3.
Not downloading older file in series: bytecode.cvd
Downloading definition file /tmp/clamav_defs/daily.cld from s3://clamav_defs/daily.cld
Downloading definition file /tmp/clamav_defs/daily.cld complete!
Starting freshclam with defs in /tmp/clamav_defs.
freshclam output:
ClamAV update process started at Fri Nov  8 12:18:02 2019
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
Downloading daily-25614.cdiff [100%]
Downloading daily-25615.cdiff [100%]
Downloading daily-25616.cdiff [100%]
Downloading daily-25617.cdiff [100%]
Downloading daily-25618.cdiff [100%]
Downloading daily-25619.cdiff [100%]
Downloading daily-25620.cdiff [100%]
Downloading daily-25621.cdiff [100%]
Downloading daily-25622.cdiff [100%]
Downloading daily-25623.cdiff [100%]
Downloading daily-25624.cdiff [100%]
ERROR: cdiff_cmd_close: Can't write to ./clamav-1b9ea5511d3e407d7c111ec492af4b84.tmp
ERROR: cdiff_apply: Can't execute command CLOSE
ERROR: cdiff_apply: Error executing command at line 1159
ERROR: getpatch: Can't apply patch
WARNING: Incremental update failed, trying to download daily.cvd
Downloading daily.cvd [100%]
WARNING: Mirror 104.16.218.84 is not synchronized.
bytecode.cld is up to date (version: 331, sigs: 94, f-level: 63, builder: anvilleg)

File does not exist: main.cld
Not uploading main.cvd because md5 on remote matches local.
Not uploading daily.cld because md5 on remote matches local.
Not uploading daily.cvd because md5 on remote matches local.
Not uploading bytecode.cld because md5 on remote matches local.
File does not exist: bytecode.cvd
Script finished at 2019/11/08 12:18:21 UTC
END RequestId: 8ec89e1a-4aa6-46b4-a722-ae768a1e8c6e
REPORT RequestId: 8ec89e1a-4aa6-46b4-a722-ae768a1e8c6e	Duration: 24134.02 ms	Billed Duration: 24200 ms	Memory Size: 512 MB	Max Memory Used: 512 MB
```

**Comment by chrisgilmerproj** [comment]
I'm re-opening this while I do more investigation. Also going to pull in #98 into this.

**Comment by chrisgilmerproj** [comment]
I have a PR #100 to test out issues locally. It's a WIP but you might try it out and see if it helps while I'm working on this.

**Comment by chrisgilmerproj** [comment]
I've done some research here and the best possible answer I have is that you've got to boost your memory up to 1024MB from 512MB. I can't seem to reproduce this exact error even when I do severely memory constrained lambdas or when I download new files from scratch but I haven't given up yet.

Can you boost your memory allocation and report if you see an issue still?

**Comment by markmckim** [comment]
Thanks @chrisgilmerproj. I’ve boosted this up to 2048 (from 512). I’ll check back in once it’s had a chance to run the daily update and let you know what my results look like. Might be Monday morning before I get a chance to check.

Thanks for the help!

**Comment by markmckim** [comment]
@chrisgilmerproj So it "appears" like bumping this from 512mb to 2048mb may indeed have resolved the issue. I think you can go ahead and close this ticket, but I can re-open if this appears again. I'm assuming maybe the ever-increasing size of the daily definitions maybe just peaked over the size able to be processed by a 512mb lambda?

**Comment by chrisgilmerproj** [comment]
@markmckim - I'm so glad this worked for you! I'll keep this open and see if we get the same feedback from other folks. I'll also probably update the documentation.

**Comment by markmckim** [comment]
Sounds good. Thanks @chrisgilmerproj !

**Comment by chrismowbray** [comment]
Bumping to 2048mb works for me. Thanks!

**Comment by chrisgilmerproj** [comment]
Glad to hear it folks!
