### ISSUE TITLE
Updating AV definitions timing out

### ISSUE THREAD

**Issue by fayaaz** [upsidetravel/bucket-antivirus-function#98]
The script makes it to [this line](https://github.com/upsidetravel/bucket-antivirus-function/blob/4a343066ec59dd781c7ddbde49cf47309529d33c/clamav.py#L118) before timing out I assume on the next line trying to start the subprocess.

This has only started happening with one of the recent commits - I couldn't tell you which one, but around the commits for fixing the `fromtimestamp` issue.

EDIT: This is happening on regardless of which commit I'm running

**Comment by chrisgilmerproj** [comment]
Thank you for bringing this to me. Could you see if upgrading to master fixes this for you? Look at #93 and #96. Also ensure that your IAM policy is up to date. I'm going to close this but if that doesn't resolve the issue I'll be happy to reopen and investigate.

**Comment by fayaaz** [comment]
I can confirm this is still happening with the latest commits - I have forked a version of this repo with minmal changes:
https://github.com/upsidetravel/bucket-antivirus-function/compare/master...Piclo:master

This doesn't seem to happen every time when running the updater function. It sometimes times out while is sometimes is successful with the below output:

```
Starting freshclam with defs in /tmp/clamav_defs.
freshclam output:
ClamAV update process started at Fri Nov  8 12:48:43 2019
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
Downloading daily-25612.cdiff [100%]
Downloading daily-25613.cdiff [100%]
Downloading daily-25614.cdiff [100%]
Downloading daily-25615.cdiff [100%]
Downloading daily-25616.cdiff [100%]
Downloading daily-25617.cdiff [100%]
Downloading daily-25618.cdiff [100%]
Downloading daily-25619.cdiff [100%]
Downloading daily-25620.cdiff [100%]
Downloading daily-25621.cdiff [100%]
Downloading daily-25622.cdiff [100%]
Downloading daily-25623.cdiff [100%]
Downloading daily-25624.cdiff [100%]
ERROR: cdiff_cmd_close: Can't write to ./clamav-dfe179b98bd172035642acf034163e1d.tmp
ERROR: cdiff_apply: Can't execute command CLOSE
ERROR: cdiff_apply: Error executing command at line 1159
ERROR: getpatch: Can't apply patch
WARNING: Incremental update failed, trying to download daily.cvd
Downloading daily.cvd [100%]
WARNING: Mirror 104.16.218.84 is not synchronized.
bytecode.cld is up to date (version: 331, sigs: 94, f-level: 63, builder: anvilleg)

File does not exist: main.cld
Not uploading main.cvd because md5 on remote matches local.
Not uploading daily.cld because md5 on remote matches local.
Not uploading daily.cvd because md5 on remote matches local.
Not uploading bytecode.cld because md5 on remote matches local.
File does not exist: bytecode.cvd
Script finished at 2019/11/08 12:49:04 UTC
```

**Comment by chrisgilmerproj** [comment]
I'm going to investigate this in #97 . I'll re-open that ticket so follow along there :)

**Comment by markmckim** [comment]
Cross posting possible solution here from #97 - I updated the memory of the lambda from 512mb to 2048mb and it seemed to resolve the issue for me. Might be worth trying that to see if it resolves your issue

**Comment by Madalosso** [comment]
> Cross posting possible solution here from #97 - I updated the memory of the lambda from 512mb to 2048mb and it seemed to resolve the issue for me. Might be worth trying that to see if it resolves your issue

Solved the issue for me as well. Thx!
